class Sura {
  final int number;
  final String nameEn;
  final String nameAr;
  final int verses;

  const Sura({
    required this.number,
    required this.nameEn,
    required this.nameAr,
    required this.verses,
  });

  static const List<Sura> allSuras = [
    Sura(number: 1, nameEn: 'Al-Fatiha', nameAr: 'الفاتحة', verses: 7),
    Sura(number: 2, nameEn: 'Al-Baqarah', nameAr: 'البقرة', verses: 286),
    Sura(number: 3, nameEn: 'Aal-E-Imran', nameAr: 'آل عمران', verses: 200),
    Sura(number: 4, nameEn: 'An-Nisa', nameAr: 'النساء', verses: 176),
    Sura(number: 5, nameEn: 'Al-Maidah', nameAr: 'المائدة', verses: 120),
    Sura(number: 6, nameEn: 'Al-Anam', nameAr: 'الأنعام', verses: 165),
    Sura(number: 7, nameEn: 'Al-Araf', nameAr: 'الأعراف', verses: 206),
    Sura(number: 8, nameEn: 'Al-Anfal', nameAr: 'الأنفال', verses: 75),
    Sura(number: 9, nameEn: 'At-Tawbah', nameAr: 'التوبة', verses: 129),
    Sura(number: 10, nameEn: 'Yunus', nameAr: 'يونس', verses: 109),
    Sura(number: 11, nameEn: 'Hud', nameAr: 'هود', verses: 123),
    Sura(number: 12, nameEn: 'Yusuf', nameAr: 'يوسف', verses: 111),
    Sura(number: 13, nameEn: 'Ar-Rad', nameAr: 'الرعد', verses: 43),
    Sura(number: 14, nameEn: 'Ibrahim', nameAr: 'إبراهيم', verses: 52),
    Sura(number: 15, nameEn: 'Al-Hijr', nameAr: 'الحجر', verses: 99),
    Sura(number: 16, nameEn: 'An-Nahl', nameAr: 'النحل', verses: 128),
    Sura(number: 17, nameEn: 'Al-Isra', nameAr: 'الإسراء', verses: 111),
    Sura(number: 18, nameEn: 'Al-Kahf', nameAr: 'الكهف', verses: 110),
    Sura(number: 19, nameEn: 'Maryam', nameAr: 'مريم', verses: 98),
    Sura(number: 20, nameEn: 'Ta-Ha', nameAr: 'طه', verses: 135),
    Sura(number: 21, nameEn: 'Al-Anbiya', nameAr: 'الأنبياء', verses: 112),
    Sura(number: 22, nameEn: 'Al-Hajj', nameAr: 'الحج', verses: 78),
    Sura(number: 23, nameEn: 'Al-Muminun', nameAr: 'المؤمنون', verses: 118),
    Sura(number: 24, nameEn: 'An-Nur', nameAr: 'النور', verses: 64),
    Sura(number: 25, nameEn: 'Al-Furqan', nameAr: 'الفرقان', verses: 77),
    Sura(number: 26, nameEn: 'Ash-Shuara', nameAr: 'الشعراء', verses: 227),
    Sura(number: 27, nameEn: 'An-Naml', nameAr: 'النمل', verses: 93),
    Sura(number: 28, nameEn: 'Al-Qasas', nameAr: 'القصص', verses: 88),
    Sura(number: 29, nameEn: 'Al-Ankabut', nameAr: 'العنكبوت', verses: 69),
    Sura(number: 30, nameEn: 'Ar-Rum', nameAr: 'الروم', verses: 60),
    Sura(number: 31, nameEn: 'Luqman', nameAr: 'لقمان', verses: 34),
    Sura(number: 32, nameEn: 'As-Sajdah', nameAr: 'السجدة', verses: 30),
    Sura(number: 33, nameEn: 'Al-Ahzab', nameAr: 'الأحزاب', verses: 73),
    Sura(number: 34, nameEn: 'Saba', nameAr: 'سبأ', verses: 54),
    Sura(number: 35, nameEn: 'Fatir', nameAr: 'فاطر', verses: 45),
    Sura(number: 36, nameEn: 'Ya-Sin', nameAr: 'يس', verses: 83),
    Sura(number: 37, nameEn: 'As-Saffat', nameAr: 'الصافات', verses: 182),
    Sura(number: 38, nameEn: 'Sad', nameAr: 'ص', verses: 88),
    Sura(number: 39, nameEn: 'Az-Zumar', nameAr: 'الزمر', verses: 75),
    Sura(number: 40, nameEn: 'Ghafir', nameAr: 'غافر', verses: 85),
    Sura(number: 41, nameEn: 'Fussilat', nameAr: 'فصلت', verses: 54),
    Sura(number: 42, nameEn: 'Ash-Shura', nameAr: 'الشورى', verses: 53),
    Sura(number: 43, nameEn: 'Az-Zukhruf', nameAr: 'الزخرف', verses: 89),
    Sura(number: 44, nameEn: 'Ad-Dukhan', nameAr: 'الدخان', verses: 59),
    Sura(number: 45, nameEn: 'Al-Jathiyah', nameAr: 'الجاثية', verses: 37),
    Sura(number: 46, nameEn: 'Al-Ahqaf', nameAr: 'الأحقاف', verses: 35),
    Sura(number: 47, nameEn: 'Muhammad', nameAr: 'محمد', verses: 38),
    Sura(number: 48, nameEn: 'Al-Fath', nameAr: 'الفتح', verses: 29),
    Sura(number: 49, nameEn: 'Al-Hujurat', nameAr: 'الحجرات', verses: 18),
    Sura(number: 50, nameEn: 'Qaf', nameAr: 'ق', verses: 45),
    Sura(number: 51, nameEn: 'Adh-Dhariyat', nameAr: 'الذاريات', verses: 60),
    Sura(number: 52, nameEn: 'At-Tur', nameAr: 'الطور', verses: 49),
    Sura(number: 53, nameEn: 'An-Najm', nameAr: 'النجم', verses: 62),
    Sura(number: 54, nameEn: 'Al-Qamar', nameAr: 'القمر', verses: 55),
    Sura(number: 55, nameEn: 'Ar-Rahman', nameAr: 'الرحمن', verses: 78),
    Sura(number: 56, nameEn: 'Al-Waqiah', nameAr: 'الواقعة', verses: 96),
    Sura(number: 57, nameEn: 'Al-Hadid', nameAr: 'الحديد', verses: 29),
    Sura(number: 58, nameEn: 'Al-Mujadila', nameAr: 'المجادلة', verses: 22),
    Sura(number: 59, nameEn: 'Al-Hashr', nameAr: 'الحشر', verses: 24),
    Sura(number: 60, nameEn: 'Al-Mumtahina', nameAr: 'الممتحنة', verses: 13),
    Sura(number: 61, nameEn: 'As-Saf', nameAr: 'الصف', verses: 14),
    Sura(number: 62, nameEn: 'Al-Jumuah', nameAr: 'الجمعة', verses: 11),
    Sura(number: 63, nameEn: 'Al-Munafiqun', nameAr: 'المنافقون', verses: 11),
    Sura(number: 64, nameEn: 'At-Taghabun', nameAr: 'التغابن', verses: 18),
    Sura(number: 65, nameEn: 'At-Talaq', nameAr: 'الطلاق', verses: 12),
    Sura(number: 66, nameEn: 'At-Tahrim', nameAr: 'التحريم', verses: 12),
    Sura(number: 67, nameEn: 'Al-Mulk', nameAr: 'الملك', verses: 30),
    Sura(number: 68, nameEn: 'Al-Qalam', nameAr: 'القلم', verses: 52),
    Sura(number: 69, nameEn: 'Al-Haqqah', nameAr: 'الحاقة', verses: 52),
    Sura(number: 70, nameEn: 'Al-Maarij', nameAr: 'المعارج', verses: 44),
    Sura(number: 71, nameEn: 'Nuh', nameAr: 'نوح', verses: 28),
    Sura(number: 72, nameEn: 'Al-Jinn', nameAr: 'الجن', verses: 28),
    Sura(number: 73, nameEn: 'Al-Muzzammil', nameAr: 'المزمل', verses: 20),
    Sura(number: 74, nameEn: 'Al-Muddaththir', nameAr: 'المدثر', verses: 56),
    Sura(number: 75, nameEn: 'Al-Qiyamah', nameAr: 'القيامة', verses: 40),
    Sura(number: 76, nameEn: 'Al-Insan', nameAr: 'الإنسان', verses: 31),
    Sura(number: 77, nameEn: 'Al-Mursalat', nameAr: 'المرسلات', verses: 50),
    Sura(number: 78, nameEn: 'An-Naba', nameAr: 'النبأ', verses: 40),
    Sura(number: 79, nameEn: 'An-Naziat', nameAr: 'النازعات', verses: 46),
    Sura(number: 80, nameEn: 'Abasa', nameAr: 'عبس', verses: 42),
    Sura(number: 81, nameEn: 'At-Takwir', nameAr: 'التكوير', verses: 29),
    Sura(number: 82, nameEn: 'Al-Infitar', nameAr: 'الانفطار', verses: 19),
    Sura(number: 83, nameEn: 'Al-Mutaffifin', nameAr: 'المطففين', verses: 36),
    Sura(number: 84, nameEn: 'Al-Inshiqaq', nameAr: 'الانشقاق', verses: 25),
    Sura(number: 85, nameEn: 'Al-Buruj', nameAr: 'البروج', verses: 22),
    Sura(number: 86, nameEn: 'At-Tariq', nameAr: 'الطارق', verses: 17),
    Sura(number: 87, nameEn: 'Al-Ala', nameAr: 'الأعلى', verses: 19),
    Sura(number: 88, nameEn: 'Al-Ghashiyah', nameAr: 'الغاشية', verses: 26),
    Sura(number: 89, nameEn: 'Al-Fajr', nameAr: 'الفجر', verses: 30),
    Sura(number: 90, nameEn: 'Al-Balad', nameAr: 'البلد', verses: 20),
    Sura(number: 91, nameEn: 'Ash-Shams', nameAr: 'الشمس', verses: 15),
    Sura(number: 92, nameEn: 'Al-Lail', nameAr: 'الليل', verses: 21),
    Sura(number: 93, nameEn: 'Ad-Duhaa', nameAr: 'الضحى', verses: 11),
    Sura(number: 94, nameEn: 'Ash-Sharh', nameAr: 'الشرح', verses: 8),
    Sura(number: 95, nameEn: 'At-Tin', nameAr: 'التين', verses: 8),
    Sura(number: 96, nameEn: 'Al-Alaq', nameAr: 'العلق', verses: 19),
    Sura(number: 97, nameEn: 'Al-Qadr', nameAr: 'القدر', verses: 5),
    Sura(number: 98, nameEn: 'Al-Bayyinah', nameAr: 'البينة', verses: 8),
    Sura(number: 99, nameEn: 'Az-Zalzalah', nameAr: 'الزلزلة', verses: 8),
    Sura(number: 100, nameEn: 'Al-Adiyat', nameAr: 'العاديات', verses: 11),
    Sura(number: 101, nameEn: 'Al-Qariah', nameAr: 'القارعة', verses: 11),
    Sura(number: 102, nameEn: 'At-Takathur', nameAr: 'التكاثر', verses: 8),
    Sura(number: 103, nameEn: 'Al-Asr', nameAr: 'العصر', verses: 3),
    Sura(number: 104, nameEn: 'Al-Humazah', nameAr: 'الهمزة', verses: 9),
    Sura(number: 105, nameEn: 'Al-Fil', nameAr: 'الفيل', verses: 5),
    Sura(number: 106, nameEn: 'Quraysh', nameAr: 'قريش', verses: 4),
    Sura(number: 107, nameEn: 'Al-Maun', nameAr: 'الماعون', verses: 7),
    Sura(number: 108, nameEn: 'Al-Kawthar', nameAr: 'الكوثر', verses: 3),
    Sura(number: 109, nameEn: 'Al-Kafirun', nameAr: 'الكافرون', verses: 6),
    Sura(number: 110, nameEn: 'An-Nasr', nameAr: 'النصر', verses: 3),
    Sura(number: 111, nameEn: 'Al-Masad', nameAr: 'المسد', verses: 5),
    Sura(number: 112, nameEn: 'Al-Ikhlas', nameAr: 'الإخلاص', verses: 4),
    Sura(number: 113, nameEn: 'Al-Falaq', nameAr: 'الفلق', verses: 5),
    Sura(number: 114, nameEn: 'An-Nas', nameAr: 'الناس', verses: 6),
  ];
}
